//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo.Analyzer {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Todo.Analyzer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string TA0001_Title {
            get {
                return ResourceManager.GetString("TA0001_Title", resourceCulture);
            }
        }
        
        internal static string TA0001_MessageFormat {
            get {
                return ResourceManager.GetString("TA0001_MessageFormat", resourceCulture);
            }
        }
        
        internal static string TA0001_Description {
            get {
                return ResourceManager.GetString("TA0001_Description", resourceCulture);
            }
        }
        
        internal static string TA0002_Title {
            get {
                return ResourceManager.GetString("TA0002_Title", resourceCulture);
            }
        }
        
        internal static string TA0002_Description {
            get {
                return ResourceManager.GetString("TA0002_Description", resourceCulture);
            }
        }
        
        internal static string TA0002_MessageFormat {
            get {
                return ResourceManager.GetString("TA0002_MessageFormat", resourceCulture);
            }
        }
        
        internal static string TA0003_Description {
            get {
                return ResourceManager.GetString("TA0003_Description", resourceCulture);
            }
        }
        
        internal static string TA0003_MessageFormat {
            get {
                return ResourceManager.GetString("TA0003_MessageFormat", resourceCulture);
            }
        }
        
        internal static string TA0003_Title {
            get {
                return ResourceManager.GetString("TA0003_Title", resourceCulture);
            }
        }
    }
}
