name: Push NuGet

on:
  release:
    types: [ published ]

jobs:
  release_nuget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test and code coverage
        shell: pwsh
        run: ./Scripts/RunTests.ps1
      - name: Push NuGet
        shell: pwsh
        run: |
          foreach($file in (Get-ChildItem "./.packages" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_API }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }